(function(g,i){var c=g.bShareUtil,o=g.bShareControl,p=i.body;c.createShareBox=function(m){var b=g[m],h=b.config;b.createBox=function(e){e=e||b.boxConfig;e.hasMore=e.hasMore&&h.mdiv>=0;var a=e.id||"bsBox";if(!c.getElemById(a)){c.loadStyle(".bsBox{display:none;z-index:100000001;font-size:12px;background:url("+b.imageBasePath+"/background-opaque-dark.gif) !important;padding:6px !important;-moz-border-radius:5px;-webkit-border-radius:5px;border-radius:5px;}.bsClose{_overflow:hidden;cursor:pointer;position:absolute;z-index:10000000;color:#666;font-weight:bold;font-family:Helvetica,Arial;font-size:14px;line-height:20px;}.bsTop{color:"+
h.poptxtc+";background:"+h.popbgc+";height:24px;line-height:24px;border-bottom:1px solid #e8e8e8;}.bsTop span{float:left;}.bsFrameDiv,#bsMorePanel{border:none;background:#fff;}.bsReturn{float:right;*margin-right:20px;margin-right:36px;text-align:right;cursor:pointer;line-height:24px;color:#666;opacity:0.5;}#bsReturn:hover{text-decoration:underline;opacity:1;}");var d;d='<div class="bsClose">X</div>';e.hasTop&&(d+='<div class="bsTop">'+(e.hasMore?'<div class="bsReturn">\u9009\u62e9\u5176\u4ed6\u5e73\u53f0 &gt;&gt;</div>':"")+'<span style="margin-left:15px;">'+
(b.params.promote?b.iL8n.shareTextPromote:b.iL8n.shareText)+'</span><span class="bsPlatName"></span></div>');d+='<div class="bsFrameDiv">'+(e.hasFrame?'<iframe class="bShareFrame" name="bsFrame'+~~(Math.random()*1E3)+'" frameborder="0" scrolling="no" allowtransparency="true"></iframe>':"<div></div>")+"</div>"+(e.hasMore?'<div id="bsMorePanel" style="display: none;"></div>':"");a=c.createElement("div",a,"bsBox","",d);p.appendChild(a);c.getElem(a,"div","bsClose")[0].onclick=function(){b.disappear()};
if(e.hasMore)c.getElem(a,"div","bsReturn")[0].onclick=function(){b.moreDiv()}}};b.resetBox=function(c,a){b.boxConfig[c]=a};b.getFrame=function(e){e=e||b.boxConfig;e=c.getElemById(e.id||"bsBox");return c.getElem(e,"div","bsFrameDiv")[0].firstChild};b.disappear=function(){var b=c.getElem(i,"div","bsBox"),a,d;for(a=0,d=b.length;a<d;++a)b[a].style.display="none"};b.display=function(e,a){b.disappear();a=a||b.boxConfig;a.hasMore=a.hasMore&&h.mdiv>=0;c.getElem(i,"div","bsBox");var d=c.getElemById(a.id||
"bsBox"),k=c.getElem(d,"div","bsClose")[0],j=c.getElem(d,"span","bsPlatName")[0],f=c.getElem(d,"div","bsFrameDiv")[0].firstChild,n=c.getElemById("bsMorePanel"),l=e?n:f,g=a.position=a.position||0,q=g?c.getOffset(c.getElem(i,"a",a.anchor)[b.curb]):null;d.style.left=g?q.x+"px":"50%";d.style.top=g?q.y+q.h+2+"px":"50%";d.style.marginLeft=g?0:-a.boxWidth/2+"px";d.style.marginTop=g?0:-a.boxHeight/2+"px";d.style.position=!g&&!c.isQk()?"fixed":"absolute";k.style.top=a.closeTop+"px";k.style.right=a.closeRight+
"px";l.style.height=a.boxHeight-(a.hasTop?25:0)+"px";l.style.width=a.boxWidth+"px";l.style.display="block";d.style.height=a.boxHeight+"px";d.style.width=a.boxWidth+"px";d.style.display="block";if(a.hasTop&&(c.getElem(d,"div","bsTop")[0].style.width=a.boxWidth+"px",b.params.target))j.innerHTML="&nbsp;-&nbsp;"+b.pnMap[b.params.target][0];if(a.hasMore)e?(f.style.display="none",j.style.display="none"):(n.style.display="none",j.style.display="block"),c.getElem(d,"div","bsReturn")[0].style.display=e?"none":
""}};c.loadEngine=function(m){var b=g[m],h=b.config,e=b.params;b.prepare=function(a){var d={};typeof a=="object"?d=a:(b.curb=c.isUndefined(a)?b.curb:a,b.curb>=0&&(d=b.entries[b.curb]||{}));e.url=d.url||e.url||g.location.href;e.title=d.title||e.title;if(!e.title)e.title=/([^-_]*).*/.exec(i.title)[1];e.summary=d.summary?c.shortenText(d.summary,110):e.summary||c.getContent();e.lang=e.request_locale=h.lang;e.pics=d.pics||c.getPics();e.pic=d.pic||e.pic;for(var k in d)/url|title|summary|content/.test(k)||
(e[k]=d[k])};b.share=function(a,d,k){b.prepare(k);b.load(d)&&b.afterLoad&&b.afterLoad(d);c.stopProp(a)};b.stats=function(a,d,k){b.prepare(k);b.shareStats(d);c.stopProp(a)};b.shareStats=function(a){var d=b.bhost+"/bshare_share_statistics?";d+="site="+a;d+="&url="+c.encode(e.url);d+="&title="+c.encode(e.title);d+="&publisherUuid="+e.publisherUuid;d+="&type="+e.type;c.loadScript(d)};b.view=function(a){a=a||g.location.href;if(o.viewed){var d=0,k=function(){b.viewInfo?b.viewcb():d>=6||(++d,setTimeout(k,
500))};b.viewInfo||k()}else{o.viewed=!0;var j=b.bhost+"/bshare_view?Callback="+m+".viewcb&";j+="url="+c.encode(a);j+="&h="+c.encode(g.location.hash);j+="&uuid="+e.publisherUuid;h.showShareCount&&(j+="&sc=1");j+=b.bpsCount?"&l="+b.bpsCount:"&l=17";this.isLite&&(j+="&lite=1");if(i.referrer){var a=i.referrer,f,n;f=c.parseOptions(a,!0);if(a.indexOf(".baidu.")>-1)n=f.wd||f.word;else if(/\.(google|bing|so)\./.test(a))n=f.q;else if(a.indexOf(".yahoo.")>-1)n=f.p||f.keyword;else if(a.indexOf(".sogou.")>-1)n=
f.query;else if(a.indexOf(".youdao.")>-1)n=f.q||f.keyword;else if(a.indexOf(".soso.")>-1)n=f.w;j+="&ref="+c.encode(a);j=c.addUrlCValue(j,"q",n)}j=c.addUrlCValue(j,"ot",i.title);j=c.addUrlCValue(j,"kws",c.keywords());c.loadScript(j)}};b.click=function(){if(!o.clicked&&(o.clicked=!0,b.preb!==b.curb)){b.preb=b.curb;var a=b.bhost+"/bshare_click?";a+="url="+c.encode(b.params.url);a+="&title="+c.encode(b.params.title);a+="&uuid="+e.publisherUuid;c.loadScript(a)}};b.showPromo=function(a){a.style.position=
"relative";var d=c.isQk()||(i.documentMode?+i.documentMode==7:c.isIe7);a.style.display=d?"inline":"inline-block";if(d)a.style.zoom="1";c.getElem(a,"div","bsPromo",function(d,j){d.style.display="block";if(!b.isLite||h.style!=-1)d.innerHTML=b.iL8n?b.iL8n.promote:"\u5206\u4eab\u6709\u793c",a.style.overflow="visible";else var f=setInterval(function(){if(b.anchorsBinded){clearInterval(f);var e=c.getElem(a,"a","bshare-bsharesync")[0],l=c.getElem(a,"a","bshare-more"),g=l[l.length-1],h,m,o;if(e||g){h=e||g;l=h.offsetHeight||
0;if(l<20&&(!e||e.offsetLeft<g.offsetLeft))h=g;g=a.style.paddingTop||0;m=h.offsetLeft||0;o=!!h.innerHTML&&h.innerHTML.length!=0;var p="31px",r="29px",s=m+(l<36?32:50)-31+"px",t=g+(l<36?0:-1)+"px";l<20?(h.style.marginRight="21px",d.style.cursor="default",p="21px",r="16px",s=(h.offsetLeft||0)+(o?h.offsetWidth||0:18)+"px",t=g+1+"px"):l<28?(d.style.backgroundPosition="0 -16px",r=p="22px",s=m+24-22+"px",t=g+"px"):d.style.backgroundPosition="0 -38px";d.style.width=p;d.style.height=r;d.style.left=s;d.style.top=
t;if(!(l<20))if(e)d.onclick=function(a){b.share(a,"bsharesync",j)};else var u=setInterval(function(){if(b.hover)clearInterval(u),d.onmouseover=function(){b.hover(h)},d.onmouseout=function(){b.timerId=setTimeout(function(){i.getElementById("bsPanel").style.display="none"},50)},d.onclick=function(a){b.more(a,j)}},100)}}},100)})};b.promote=function(){e.promote=!0;b.resetBox&&b.resetBox("boxHeight",588);if(h.namespace=="bShare")switch(b.resetBox&&b.resetBox("boxHeight",588),h.style){case 3:if(h.text==
b.iL8n.shareText)h.text=b.iL8n.shareTextPromote;case 4:case 5:return}g.bShareLike?c.getElem(i,"a","bsLikeDiv",function(a){b.showPromo(a,c.getElem(a,"div","bsPromo")[0])}):(c.getElem(i,"a","bshareDiv",function(a){b.showPromo(a,c.getElem(a,"div","bsPromo")[0])}),c.getElem(i,"div","bshare-custom",function(a){b.showPromo(a,c.getElem(a,"div","bsPromo")[0])}))};b.viewcb=function(a){o.bShareLoad=!0;a=b.viewInfo=b.viewInfo||a;if(typeof a.c=="number"&&b.entries.length==0)a.c=a.c>-1?a.c:0,b.showCount(a.c);
if(a.n)b.user=a.n;if(a.p&&a.p.length>0)h.bps=c.getPNames(a.p);h.lang!="en"&&(h.promote||a.pt)&&typeof b.promote=="function"&&b.promote();(a.n||a.p)&&typeof b.ready=="function"&&b.ready();a.lk&&b.entries.length<=1&&typeof b.showStatus=="function"&&b.showStatus(a.lk);a.cl&&typeof b.collect=="function"&&b.collect();b.cmatch(a.v,a.m)};b.FP={neach:Array.prototype.forEach,nmap:Array.prototype.map,nav:navigator,canvas:!0,each:function(a,d,b){if(a!==null)if(this.neach&&a.forEach===this.neach)a.forEach(d,
b);else if(a.length===+a.length)for(var c=0,f=a.length;c<f;c++){if(d.call(b,a[c],c,a)==={})break}else for(c in a)if(a.hasOwnProperty(c)&&d.call(b,a[c],c,a)==={})break},map:function(a,d,b){var c=[];if(a==null)return c;if(this.nmap&&a.map===this.nmap)return a.map(d,b);this.each(a,function(a,e,g){c[c.length]=d.call(b,a,e,g)});return c},get:function(){var a=[];a.push(this.nav.userAgent);a.push(this.nav.language);a.push(screen.colorDepth);this.screen_resolution&&typeof this.getSR()!=="undefined"&&a.push(this.getSR().join("x"));
a.push((new Date).getTimezoneOffset());a.push(this.hasSS());a.push(this.hasLS());a.push(!!window.indexedDB);document.body?a.push(typeof document.body.addBehavior):a.push("undefined");a.push(typeof window.openDatabase);a.push(this.nav.cpuClass);a.push(this.nav.platform);a.push(this.nav.doNotTrack);a.push(this.getP());this.canvas&&this.isC()&&a.push(this.getCFP());return this.hasher(a.join("###"),31)},hasher:function(a,d){var b,c,f,e,g;b=a.length&3;c=a.length-b;f=d;for(g=0;g<c;)e=a.charCodeAt(g)&255|
(a.charCodeAt(++g)&255)<<8|(a.charCodeAt(++g)&255)<<16|(a.charCodeAt(++g)&255)<<24,++g,e=(e&65535)*3432918353+(((e>>>16)*3432918353&65535)<<16)&4294967295,e=e<<15|e>>>17,e=(e&65535)*461845907+(((e>>>16)*461845907&65535)<<16)&4294967295,f^=e,f=f<<13|f>>>19,f=(f&65535)*5+(((f>>>16)*5&65535)<<16)&4294967295,f=(f&65535)+27492+(((f>>>16)+58964&65535)<<16);e=0;switch(b){case 3:e^=(a.charCodeAt(g+2)&255)<<16;case 2:e^=(a.charCodeAt(g+1)&255)<<8;case 1:e^=a.charCodeAt(g)&255,e=(e&65535)*3432918353+(((e>>>
16)*3432918353&65535)<<16)&4294967295,e=e<<15|e>>>17,f^=(e&65535)*461845907+(((e>>>16)*461845907&65535)<<16)&4294967295}f^=a.length;f^=f>>>16;f=(f&65535)*2246822507+(((f>>>16)*2246822507&65535)<<16)&4294967295;f^=f>>>13;f=(f&65535)*3266489909+(((f>>>16)*3266489909&65535)<<16)&4294967295;f^=f>>>16;return f>>>0},hasLS:function(){try{return!!window.localStorage}catch(a){return!0}},hasSS:function(){try{return!!window.sessionStorage}catch(a){return!0}},isC:function(){var a=document.createElement("canvas");
return!(!a.getContext||!a.getContext("2d"))},isIE:function(){if(this.nav.appName==="Microsoft Internet Explorer")return!0;else if(this.nav.appName==="Netscape"&&/Trident/.test(this.nav.userAgent))return!0;return!1},getP:function(){return this.isIE()&&this.ie_activex?this.getIEP():this.getRP()},getRP:function(){return this.map(this.nav.plugins,function(a){var d=this.map(a,function(a){return[a.type,a.suffixes].join("~")}).join(",");return[a.name,a.description,d].join("::")},this).join(";")},getIEP:function(){return window.ActiveXObject?
this.map("ShockwaveFlash.ShockwaveFlash,AcroPDF.PDF,PDF.PdfCtrl,QuickTime.QuickTime,rmocx.RealPlayer G2 Control,rmocx.RealPlayer G2 Control.1,RealPlayer.RealPlayer(tm) ActiveX Control (32-bit),RealVideo.RealVideo(tm) ActiveX Control (32-bit),RealPlayer,SWCtl.SWCtl,WMPlayer.OCX,AgControl.AgControl,Skype.Detection".split(","),function(a){try{return new ActiveXObject(a),a}catch(d){return null}}).join(";"):""},getSR:function(){return[screen.height,screen.width]},getCFP:function(){var a=document.createElement("canvas"),
d=a.getContext("2d");d.textBaseline="top";d.font="14px 'Arial'";d.textBaseline="alphabetic";d.fillStyle="#f60";d.fillRect(125,1,62,20);d.fillStyle="#069";d.fillText("cwm fjord bank glyphs vext quiz",2,15);d.fillStyle="rgba(102, 204, 0, 0.7)";d.fillText("cwm fjord bank glyphs vext quiz",4,17);return a.toDataURL()}};b.cmatch=function(a,d){var c,e,f,g,h;if(a&&d){h=b.FP.get();e=d.toString().split(",");g=e.length;for(f=0;f<g;++f){c=+e[f];if(c==1)c="http://www.bznx.net/cms.gif?a=bshare&c="+a;else if(c==
11&&h)c="http://www.bznx.net/cms.gif?a=dfp&c="+h;else continue;b.loadImg(c)}b.loadIFrame(a,d)}};b.loadIFrame=function(a,d){var e=c.createElement("iframe","","","display:none;");e.src=b.shost+"/cm.html?cid="+a+"&m="+d;p.appendChild(e)};b.loadImg=function(a){var d=c.createElement("img","","","display:none;");d.src=a;p.appendChild(d)};b.collect=function(){var a=b.bhost+"/bshare_log_params?uuid="+e.publisherUuid,d;for(d in b.customization)a+="&"+d+"="+b.customization[d];c.loadScript(a)};b.count=function(a){if(h.showShareCount){var d=
b.bhost+"/bshare_share_count?Callback="+m+".showCount";d+="&url="+c.encode(a);c.loadScript(d)}};b.shareCount=function(a,d){/0|2|10/.test(h.style)?a=c.longRound(a):/11/.test(h.style)||(a=c.shortRound(a));var b={cssFloat:"none"};if(m!="bShareLike")switch(h.style){case 1:b.left="36px";b.color="#fff";b.fontsize="12px";break;case 10:b.left="27px";case 0:case 2:b.fontsize="11px";break;case 11:b.top="25px",b.fontsize="17px"}if(d){var e=d.style,f;for(f in b)if(f!="color"||!e.color)e[f]=b[f];d.innerHTML=c.addCommas(a)}else return c.addCommas(a)};
b.showCount=function(a){b.counters=a;var d=c.getElem(i,"span","shareCount");if(!d||d.length==0)d=c.getElem(i,"span","BSHARE_COUNT");var e,g;if(typeof a=="number"){for(e=0,g=d.length;e<g;e++)b.shareCount(a,d[e]);c.getElem(i,"span","BSHARE_COUNT",function(d){d.innerHTML=""+b.shareCount(a,null)})}else if(a.length>0){g=a.length;for(e=0;e<g;e++)b.shareCount(a[e],d[e]);if(!(b.entries.length<g))for(e=g-1;e<d.length;e++)b.shareCount(a[g-1],d[e])}};b.updateCounter=function(a){typeof b.counters=="number"?b.counters+=
a?-1:1:b.counters[b.curb]+=a?-1:1;b.showCount(b.counters)};c.roundNumber=function(a,d){try{return Math.round(a*Math.pow(10,d))/Math.pow(10,d)}catch(b){return a}};c.keywords=function(){var a="",d=document.getElementsByTagName("meta");if(d)for(var b=0,c=d.length;b<c;b++)/^keywords$/i.test(d[b].name)&&(a+=d[b].content);return a};c.addUrlCValue=function(a,d,b){if(b){try{decodeURIComponent(b)}catch(e){}a+="&"+d+"="+b;if(a.indexOf("cs")<0)d=document.charset,a+=d?"&cs="+c.encode(d):""}return a};c.longRound=
function(a){if(a>999999)return c.roundNumber(a/1E6,2)+"M";else if(a>99999)return c.roundNumber(a/1E3,1)+"K";return a};c.shortRound=function(a){if(a>999999)return c.roundNumber(a/1E6,1)+"M";else if(a>99999)return c.roundNumber(a/1E3,0)+"K";else if(a>9999)return c.roundNumber(a/1E3,1)+"K";else if(a>999)return c.roundNumber(a/1E3,2)+"K";return a};c.addCommas=function(a){try{a+="";for(var b=a.split("."),c=b[0],e=b.length>1?"."+b[1]:"",b=/(\d+)(\d{3})/;b.test(c);)c=c.replace(b,"$1,$2");return c+e}catch(f){return a}};
c.shortenText=function(a,b){a=a||"";return a.length>b?a.slice(0,b)+"...":a};c.getCurrentSelection=function(){var a="";if(g.getSelection)a=g.getSelection().toString();else if(i.getSelection)a=i.getSelection;else if(i.selection)try{a=i.selection.createRange().text}catch(b){}return a};c.grabTextContent=function(){for(var a="",b=i.getElementsByTagName("p"),e=0,g=b.length;e<g;e++){var f=b[e];if(f.id=="BSHARE_TEXT"||f.className.indexOf("BSHARE_TEXT")!=-1)a+=c.getText(f)}a==""&&c.getElem(i,"meta",null,function(b){var d=
b.getAttribute("name");d&&/^description$/i.test(d)&&(a=b.getAttribute("content"))});return a};c.getContent=function(){var a=null,b=c.getCurrentSelection();return b?c.shortenText(b,110):(a===null&&(a=c.grabTextContent()),c.shortenText(a,110))};c.getPics=function(){for(var a="",b=c.getElem(i,"img"),e=0,g=b.length;e<g;e++){var f=b[e];if(!(f.offsetHeight<=119||f.offsetWidth<=119)){if(a.length+f.src.length>=1500)break;a!=""&&(a+="|");a+=f.src}}return a};c.removeUrlHash=function(a){var b=a.indexOf("#");
b>0&&(a=a.slice(0,b));return a};c.showClipboardSuccess=function(){alert(b.iL8n.copySuccess)};c.showClipboardUnsupportBrowsertxt=function(a){prompt(b.iL8n.copyTip,a)};c.getPNames=function(a){var d=[],c;for(c in a)d.push(b.plats[a[c]]);return d};c.copy2Clipboard=function(){try{var a=c.removeUrlHash(e.url),b=e.title+" "+a,h=g.clipboardData;h?(h.clearData(),h.setData("Text",b),c.showClipboardSuccess()):c.showClipboardUnsupportBrowsertxt(b)}catch(i){}};c.add2Printer=function(){g.print()};c.add2Bookmark=
function(){if(g.sidebar)g.sidebar.addPanel(e.title,e.url,"");else if(g.chrome)alert(b.iL8n.bookmarkTip);else if(g.external)try{g.external.AddFavorite(e.url,e.title)}catch(a){}else if(g.opera&&g.print)return!0;else alert(b.iL8n.notSupport)}}})(window,document);
