(function(){function I(){var d=[],c,a=e.getElem(j,"div",J);if(a.length>0)for(c=0;c<a.length;++c)d=d.concat(e.getElem(a[c],"img"));else d=e.getElem(j,"img");for(c=0;c<d.length;c++){var b=d[c],f=b.parentNode,a=b.className,h=b.offsetHeight,i=b.offsetWidth;if(!(A!="BSHARE_IMAGE_ALL"&&a.indexOf(A)==-1)&&!(h!=0&&h<v||i!=0&&i<w))if(!(a.indexOf(E)!=-1||a=="bshare-logos")&&!(/^a$/i.test(f.nodeName)&&f.parentNode===null)){if(/^a$/i.test(f.nodeName))b=f,f=b.parentNode;var h=l(b,k?"marginLeft":"margin-left"),
i=l(b,k?"marginRight":"margin-right"),o=l(b,k?"marginTop":"margin-top"),p=l(b,k?"marginBottom":"margin-bottom"),q=l(b,k?"paddingLeft":"padding-left"),r=l(b,k?"paddingRight":"padding-right"),s=l(b,k?"paddingTop":"padding-top"),t=l(b,k?"paddingBottom":"padding-bottom");b.style.padding=0;b.style.margin=0;f.className.indexOf("bshare-image2share")>-1?a=f:(a=e.createElement("div","","bshare-image2share"),a.appendChild(b.cloneNode(!0)),f.insertBefore(a,b),f.removeChild(b));if(u)try{h=h?+h.slice(0,h.length-
2):0,i=i?+i.slice(0,i.length-2):0,o=o?+o.slice(0,o.length-2):0,p=p?+p.slice(0,p.length-2):0,q=q?+q.slice(0,q.length-2):0,r=r?+r.slice(0,r.length-2):0,s=s?+s.slice(0,s.length-2):0,t=t?+t.slice(0,t.length-2):0,a.style.marginLeft=h+q-3+"px",a.style.marginRight=i+r-3+"px",a.style.marginTop=o+s-3+"px",a.style.marginBottom=p+t-3+"px"}catch(z){}b=e.createElement("span","","bshare-overlayLink","display:none;");if(F)f=e.createElement("a","","bshare-buzz"),f.href=g.whost+"/imageSharing",f.target="_blank",h=
e.createElement("img","bsharemore","bshare-logos"),h.src=g.shost+"/frame/images/logo_square_s.gif",h.title=x.whatsThis,f.appendChild(h),b.appendChild(f);f=e.createElement("span","","bshare-textspan","",B);b.appendChild(f);for(f=0;f<C.length;f++)if(h=C[f],!e.isUndefined(g.pnMap[h]))i=e.createElement("img",h,"bshare-logos"),i.src=K+h+(k?".gif":".png"),i.title=x.shareText+" "+g.pnMap[h][0],b.appendChild(i);a.appendChild(b)}}var n=0;g.addEntry({pic:""});n=g.entries.length-1;if(j.addEventListener){d=e.getElem(j,
"span","bshare-overlayLink");for(c=0;c<d.length;c++){a=d[c].getElementsByTagName("img");for(b=0;b<a.length;b++)a[b].addEventListener("click",function(a){var b=this.parentNode.parentNode.getElementsByTagName("img")[0];g.entries[n].pic=b.src;if(b.alt)g.entries[n].summary=b.alt;this.id!="bsharemore"&&g.share(a,this.id,n);e.stopProp(a);return!1},!1)}d=e.getElem(j,"div","bshare-image2share");for(c=0;c<d.length;c++)d[c].addEventListener("mouseover",function(){var a=this.getElementsByTagName("img")[0];if(!(a.offsetHeight<
v||a.offsetWidth<w))this.style.background=y,this.getElementsByTagName("span")[0].style.display="block"},!1),d[c].addEventListener("mouseout",function(){this.style.background="transparent";this.getElementsByTagName("span")[0].style.display="none"},!1)}else if(j.attachEvent){d=e.getElem(j,"span","bshare-overlayLink");for(c=0;c<d.length;c++){a=d[c].getElementsByTagName("img");for(b=0;b<a.length;b++)a[b].attachEvent("onclick",function(a){if(!a)a=m.event;var b=a.target?a.target:a.srcElement;if(b){var c=
b.parentNode.parentNode.getElementsByTagName("img")[0];g.entries[n].pic=c.src;if(c.alt)g.entries[n].summary=c.alt;if(b.id=="bsharemore")return!0;else g.share(a,b.id,n);e.stopProp(a);return!1}})}d=e.getElem(j,"div","bshare-image2share");for(c=0;c<d.length;c++)d[c].attachEvent("onmouseenter",function(a){if(!a)a=m.event;if(a=a.target?a.target:a.srcElement){var b=a.getElementsByTagName("img")[0];if(!(b.offsetHeight<v||b.offsetWidth<w))a.style.background=y,a.getElementsByTagName("span")[0].style.display=
"block"}},!1),d[c].attachEvent("onmouseleave",function(a){if(!a)a=m.event;if(a=a.target?a.target:a.srcElement)a.style.background="transparent",a.getElementsByTagName("span")[0].style.display="none"},!1)}typeof g.bshareMMOnReady=="function"&&g.bshareMMOnReady()}function l(d,c){return d.currentStyle?d.currentStyle[c]:m.getComputedStyle?j.defaultView.getComputedStyle(d,null).getPropertyValue(c):""}var G=!1,m=window,j=document,e=m.bShareUtil,g=m.bShare,x=g.iL8n||{},K=g.imageBasePath+"logos/s4/",k=e.isIe,
J="BSHARE_IMAGE_CLASS",y="#FF5C00",z="#FF5C00",H="#FFF",C="qqmb,sinaminiblog,renren,sohuminiblog,neteasemb,msn".split(","),E="BSHARE_IMAGE_NO",A="BSHARE_IMAGE",v=20,w=100,F=!0,u=!0,D=2,B,L=e.isQk()||(j.documentMode?+j.documentMode==7:e.isIe7);e.ready(function(){var d=function(){if(g.completed){x=g.iL8n;B=x.shareText;var c=e.getScript(/bshareMM/)[0],a={};if(!e.isUndefined(m.bShareOpt))a=m.bShareOpt;if(c){var c=e.parseOptions(c.src),b;for(b in c)a[b]=c[b]}if(a.bgColor)z=a.bgColor;if(a.txtColor)H=a.txtColor;
if(a.text)B=a.text;if(a.shareClass)A=a.shareClass;if(a.noShareClass)E=a.noShareClass;if(a.minHeight)v=a.minHeight;if(a.minWidth)w=a.minWidth;a.bp&&(C=a.bp.split(","));a.border&&(u=/^true$/i.test(a.border));a.pos&&(b=+a.pos,b>0&&b<5&&(D=b));F=!(a.logo&&/^false$/i.test(a.logo));a="";if(u)switch(y=z,D){case 1:a="left:3px;top:3px;";break;case 3:a="right:3px;*right:2px;bottom:3px;";break;case 4:a="left:3px;bottom:3px;";break;default:a="right:3px;*right:2px;top:3px;"}else switch(y="transparent",D){case 1:a=
"left:0;top:0;";break;case 3:a="right:0;bottom:0;*bottom:-1px;";break;case 4:a="left:0;bottom:0;*bottom:-1px;";break;default:a="right:0;top:0;"}e.loadStyle(".bshare-buzz{float:left;}.bshare-overlayLink{position:absolute;padding:"+(u?"0 3px ":"")+"3px;"+a+"background-color:"+z+";text-indent:0;line-height:normal;}.bshare-textspan{float:left;font-family:Arial,\u5b8b\u4f53,sans-serif;line-height:16px;font-size:13px;color:"+H+";vertical-align:bottom;font-weight:bold;padding:0 2px;}img.bshare-logos{width:auto !important;height:auto !important;vertical-align:bottom;float:left;padding:0 2px !important;cursor:pointer;border:none !important;margin:0 !important;margin:0 2px9;}.bshare-image2share{"+
(u?"margin:-3px;padding:3px;":"")+"position:relative;zoom:1;background:transparent;text-indent:0;line-height:0;"+(L?"display:inline;zoom:1;":"display:inline-block;")+"}");setTimeout(I,3E3)}else setTimeout(d,50)};G||(G=!0,d())})})();
