document.writeln("<script type=\"text/javascript\" src=\"/forumdata/jscaches/js_forumlist.js\"></script>");
document.writeln("<div class=\"headermenu_popup\" id=\"tplselect_menu\" style=\"display: none\">");
document.writeln("	<table cellspacing=\"1\" cellpadding=\"5\" border=\"0\" class=\"popupmenu_option2\">");
document.writeln("		<tr>");
document.writeln("			<td valign=\"top\" nowrap><a href=\"javascript:seltpl(0)\">恢复默认设置</a><br />");
document.writeln("			<a href=\"javascript:seltpl(37)\">默认模板</a><br />");
document.writeln("			<a href=\"javascript:seltpl(25)\">水晶紫色</a><br />");
document.writeln("			<a href=\"javascript:seltpl(26)\">ｅ点小镇</a><br />");
document.writeln("			<a href=\"javascript:seltpl(27)\">心情灰色</a><br />");
document.writeln("			<a href=\"javascript:seltpl(28)\">秋意盎然</a><br />");
document.writeln("			<a href=\"javascript:seltpl(29)\">蓝色庄重</a><br />");
document.writeln("			<a href=\"javascript:seltpl(32)\">绿色淡雅</a><br />");
document.writeln("			<a href=\"javascript:seltpl(34)\">蓝雅绿</a><br />");
document.writeln("			<a href=\"javascript:seltpl(35)\">紫色淡雅</a><br />");
document.writeln("			<a href=\"javascript:seltpl(36)\">淡紫色</a><br />");
document.writeln("			<a href=\"javascript:seltpl(37)\">橘子红了</a><br />");
document.writeln("			<a href=\"javascript:seltpl(38)\">红红夜思</a><br />");
document.writeln("			<a href=\"javascript:seltpl(40)\">粉色回忆</a><br />");
document.writeln("			<a href=\"javascript:seltpl(41)\">青青河草</a><br />");
document.writeln("			<a href=\"javascript:seltpl(42)\">浓浓绿意</a><br />");
document.writeln("			<a href=\"javascript:seltpl(44)\">棕红预览</a><br />");
document.writeln("			<a href=\"javascript:seltpl(45)\">淡咖啡</a><br />");
document.writeln("			<a href=\"javascript:seltpl(46)\">碧海晴天</a><br />");
document.writeln("			<a href=\"javascript:seltpl(47)\">蓝色水晶</a><br />");
document.writeln("			<a href=\"javascript:seltpl(48)\">雪花飘飘</a><br />");
document.writeln("			<a href=\"javascript:seltpl(51)\">蓝色温柔</a></td>");
document.writeln("			<td valign=\"top\" nowrap><a href=\"javascript:seltpl(52)\">火红</a><br />");
document.writeln("			<a href=\"javascript:seltpl(53)\">粉蓝</a><br />");
document.writeln("			<a href=\"javascript:seltpl(54)\">橙黄</a><br />");
document.writeln("			<a href=\"javascript:seltpl(55)\">草绿</a><br />");
document.writeln("			<a href=\"javascript:seltpl(56)\">灰白</a><br />");
document.writeln("			<a href=\"javascript:seltpl(57)\">格绿</a><br />");
document.writeln("			<a href=\"javascript:seltpl(58)\">棕红</a><br />");
document.writeln("			<a href=\"javascript:seltpl(59)\">秋实</a><br />");
document.writeln("			<a href=\"javascript:seltpl(60)\">紫色</a><br />");
document.writeln("			<a href=\"javascript:seltpl(61)\">海蓝</a><br />");
document.writeln("			<a href=\"javascript:seltpl(62)\">春意</a><br />");
document.writeln("			<a href=\"javascript:seltpl(63)\">青绿</a><br />");
document.writeln("			<a href=\"javascript:seltpl(64)\">粉紫</a><br />");
document.writeln("			<a href=\"javascript:seltpl(65)\">深红</a><br />");
document.writeln("			<a href=\"javascript:seltpl(66)\">黑白</a><br />");
document.writeln("			<a href=\"javascript:seltpl(67)\">桃红</a><br />");
document.writeln("			<a href=\"javascript:seltpl(68)\">水蓝</a><br />");
document.writeln("			</td>");
document.writeln("		</tr>");
document.writeln("	</table>");
document.writeln("</div>");
document.writeln("<div class=\"headermenu_popup\" id=\"tools_menu\" style=\"display: none\">");
document.writeln("	<table cellpadding=\"4\" cellspacing=\"0\" border=\"0\">");
document.writeln("		<tr>");
document.writeln("			<td class=\"popupmenu_option2\">");
document.writeln("                                <a href=\"http://bbs.voc.com.cn/app/tuijian/index.php\" style=\"color:red\" target=_blank>版主推荐</a><br>");
document.writeln("                                <a href=\"http://bbs.voc.com.cn/app/lucky/\" style=\"color:red\" target=_blank>华声零点大转盘</a><img src=\"/images/dvbbs0/today.gif\" border=\"0\"><br>");
document.writeln("                                <a href=\"http://bbs.voc.com.cn/plugin.php?identifier=get_money&module=money\" style=\"color:blue\" target=_blank>领取红包</a><img src=\"/images/dvbbs0/today.gif\" border=\"0\"><br>");
document.writeln("			<a href=\"http://bbs.voc.com.cn/plugin.php?identifier=blcar&module=blcar\" style=\"color:#ff0066\" target=_blank>华声停车大战</a><img src=\"/images/dvbbs0/today.gif\" border=\"0\"><br>");
document.writeln("			<a href=\"/plusWebtools.php?mod=cxx\" style=\"color:green\" target=\"_blank\">超级计算器</a><br>");
document.writeln("			<a href=\"/lovewall.php\" style=\"color: #ff0066\" target=\"_blank\">华声爱墙</a><br>");
document.writeln("			<a href=\"http://net.hnol.net/ubb.htm\" target=\"_blank\">");
document.writeln("			<font color=\"blue\">华声贴图易</font></a><br>");
document.writeln("			<a href=\"/bank.php\" target=\"_blank\">华声电子银行</a><br>");
document.writeln("			<!--a href=\"http://bbs.voc.com.cn/plugin.php?identifier=modpay&module=modpay\" target=\"_blank\" style=\"color: #ff0066\" >版主工资</a-->");
document.writeln("			</td>");
document.writeln("		</tr>");
document.writeln("	</table>");
document.writeln("</div>");
document.writeln("<div class=\"headermenu_popup\" id=\"forumlistdiy_menu\" style=\"width:756px;margin:0px auto;display:none\">");
document.writeln("	<table cellpadding=\"4\" cellspacing=\"0\" border=\"0\" style=\"height: 100%; width: 100%\">");
document.writeln("		<tr>");
document.writeln("			<td class=\"popupmenu_option2\">");
document.writeln("                                <center><font color=\"red\">************************<b>华声推荐</b>************************</font></center>");
document.writeln("<div style=\"font-size:13px;\">");
document.writeln("<a href=\"/forum-76-1.html\">辣眼时评</a>　<a href=\"/forum-49-1.html\">参考文摘</a>　<a href=\"/forum-57-1.html\">图说历史</a>　<a href=\"/forum-24-1.html\">军事贴图</a>　<a href=\"/forum-70-1.html\">军事杂谈</a>　<a href=\"/forum-25-1.html\">战史风云</a>　<a href=\"/forum-61-1.html\">绝美图库</a>　<a href=\"/forum-105-1.html\">特效绝美</a>　<a href=\"http://mm.voc.com.cn/\">美女贴图</a>　<a href=\"/forum-244-1.html\">湖南论坛区</a>　<a href=\"/forum-268-1.html\">女性区</a><br>");
document.writeln("");
document.writeln("<a href=\"/forum-22-1.html\">网友自拍</a>　<a href=\"/forum-55-1.html\">Flash帝国</a>　<a href=\"/forum-77-1.html\">音乐地带</a>　<a href=\"/forum-39-1.html\">驴友自助</a>　<a href=\"/forum-164-1.html\">华声瘦客</a>　<a href=\"http://www.0731go.cn/\">长沙网</a>　<a href=\"/forum-72-1.html\">摄友摄色</a>　<a href=\"/forum-89-1.html\">情感酒廊</a>　<a href=\"/forum-83-1.html\">搞笑图库</a>　<a href=\"/forum-78-1.html\">影视时空</a>　<a href=\"search.php?srchfrom=69000&amp;orderby=dateline&amp;searchsubmit=yes\" target=\"_blank\"><span class=\"huang1\"><b>最新300帖</b></span></a><br>");
document.writeln("");
document.writeln("<a href=\"/forum-64-1.html\">娱乐八卦</a>　<a href=\"/forum-21-1.html\">千奇百怪</a>　<a href=\"/forum-52-1.html\">哈哈笑话</a>　<a href=\"/forum-56-1.html\">智力考场</a>　<a href=\"/forum-133-1.html\">混在深圳</a>　<a href=\"/forum-60-1.html\">灌水专区</a>　<a href=\"/forum-7-1.html\">光阴故事|小说</a>　<a href=\"/forum-8-1.html\">不拍不快|杂文</a><br>");
document.writeln("");
document.writeln("<a href=\"http://bbs.voc.com.cn/app/tuijian/index.php\" style=\"color:#FF6201;font-weight:bold\" target=\"_blank\">版主推荐</a><br />");
document.writeln("</div>");
document.writeln("");
document.writeln(" <center><font color=\"red\">************************<b>分类版块</b>************************</font></center>");
document.writeln("");
document.writeln("			<a href=\"/forum-47-1.html\"><span class=\"huang1\"><b>[时政军事]</b></span></a>");
document.writeln("			<a href=\"/forum-76-1.html\">辣眼时评</a>　<a href=\"/forum-49-1.html\">参考文摘</a>　<a href=\"/forum-57-1.html\">图说历史</a> <a  href=\"http://dsj.voc.com.cn/\" target='_blank'>大视界</a>　<a href=\"/forum-68-1.html\">新闻聚焦</a>　<a href=\"/forum-362-1.html\">钟山说事</a>  <a href=\"/forum-24-1.html\">军事贴图</a>　<a href=\"/forum-70-1.html\">军事杂谈</a>　<a href=\"/forum-25-1.html\">战史风云</a>　<a href=\"/forum-341-1.html\">湖南老兵之家</a>　<br />");
document.writeln("	");
document.writeln("			<a href=\"/forum-4-1.html\"><span class=\"huang1\"><b>[精彩贴图]</b></span></a>");
document.writeln("			<a href=\"http://mm.voc.com.cn/\">美女贴图</a>　<a href=\"/forum-61-1.html\">绝美图库</a>　<a href=\"/forum-83-1.html\">搞笑图库</a>　<a href=\"/forum-22-1.html\">网友自拍</a>　<a href=\"/forum-72-1.html\">摄友摄色</a><br />");
document.writeln("");
document.writeln("			<a href=\"/forum-294-1.html\"><span class=\"huang1\"><b>[华声音画]</b></span></a>");
document.writeln("			<a href=\"/forum-105-1.html\">特效绝美</a>　<a href=\"/forum-233-1.html\">单幅音画</a>　<a href=\"/forum-345-1.html\">音画心情</a>　　<a href=\"/forum-320-1.html\"><span class=\"huang1\"><b>[音画学堂]</b></span></a>  <a href=\"/forum-163-1.html\">教程交流</a>  <a href=\"/forum-321-1.html\">学员教程</a>  <a href=\"/forum-322-1.html\">作业投递</a>  <a href=\"/forum-323-1.html\">学堂教务</a><br /> ");
document.writeln("");
document.writeln("                                <a href=\"/forum-326-1.html\"><span class=\"huang1\"><b>[音画资源]</b></span></a>");
document.writeln("				<a href=\"forum-117-1.html\" target='_blank'>图片素材</a>   <a href=\"forum-328-1.html\" target='_blank'>其他资源</a> <a href=\"/forum-324-1.html\"><span class=\"huang1\"><b>[华声动漫]</b></span></a>   <a href=\"forum-325-1.html\" target='_blank'>动漫学坊</a> <a href=\"forum-55-1.html\" target='_blank'>FLASH帝国</a>  <br />");
document.writeln("");
document.writeln("			<a href=\"/forum-20-1.html\"><span class=\"huang1\"><b>[影音帝国]</b></span></a>");
document.writeln("			<a href=\"/forum-77-1.html\">音乐地带</a>　<a href=\"/forum-78-1.html\">影视时空</a>　<a href=\"forum-371-1.html\" target='_blank'>音乐快递</a>　<a href=\"/forum-112-1.html\">原声地带</a>　<a href=\"/forum-236-1.html\">高品质单曲</a>　<a href=\"/forum-343-1.html\">心情音乐</a>  <a href=\"/forum-365-1.html\">心情吟诵</a>  <a href=\"/forum-344-1.html\">音乐播放器</a><br />");
document.writeln("			<a href=\"/forum-13-1.html\"><span class=\"huang1\"><b>[轻松休闲]</b></span></a>");
document.writeln("			<a href=\"/forum-64-1.html\">娱乐八卦</a>　<a href=\"/forum-21-1.html\">千奇百怪</a>　<a href=\"/forum-80-1.html\">异度空间</a>　<a href=\"/forum-52-1.html\">哈哈笑话</a>　<a href=\"/forum-111-1.html\">异域风情</a>　<a href=\"/forum-60-1.html\">灌水专区</a>　<a href=\"/forum-56-1.html\">智力考场</a>　<a href=\"/forum-84-1.html\">体坛风云</a>　<a href=\"/forum-98-1.html\">打油部落</a>　<a href=\"/forum-300-1.html\">网游交流</a>　<a href=\"/forum-375-1.html\" target='_blank'>华声彩票</a><br />");
document.writeln("");
document.writeln("<a href=\"/forum-356-1.html\"><span class=\"huang1\"><b>[网际风云|游戏]</b></span></a>");
document.writeln("                                <a href=\"/forum-357-1.html\">诸侯争霸</a>　<a href=\"/forum-2-1.html\">听雪江湖</a>　<a href=\"/forum-358-1.html\">凭栏试剑</a>　<a href=\"/forum-359-1.html\">流金岁月</a>　<a href=\"/forum-360-1.html\">高山流水</a>　<a href=\"/forum-361-1.html\">彼岸如烟</a>　<a href=\"/forum-377-1.html\">手游天下</a><br />	");
document.writeln(" ");
document.writeln("<a href=\"/forum-268-1.html\"><span class=\"huang1\"><b>[女 性 区]</b></span></a>");
document.writeln("			<a href=\"/forum-270-1.html\">美容护肤</a>　<a href=\"/forum-269-1.html\">服饰潮流</a>　<a href=\"/forum-272-1.html\">DIY手工</a>　<a href=\"/forum-271-1.html\">女人心事</a>　<a href=\"/forum-216-1.html\">华声婚嫁</a>　<a href=\"/forum-239-1.html\">育儿论坛</a>　<a href=\"/forum-260-1.html\">花生购</a>  <a href=\"/forum-298-1.html\">珠宝首饰</a>　<a href=\"/forum-295-1.html\"><span class=\"huang1\"><b>[华声情感]</b></span></a>  <a href=\"/forum-89-1.html\">情感酒廊</a>　<a href=\"/forum-114-1.html\">菁菁校园</a><br />");
document.writeln("		");
document.writeln("			<a href=\"/forum-17-1.html\"><span class=\"huang1\"><b>[华声驴友]</b></span></a>");
document.writeln("                                <a href=\"/forum-39-1.html\">游记·影像</a>　<a href=\"/forum-189-1.html\">召集·约伴</a>　<a href=\"/forum-346-1.html\">出走社</a>　<a href=\"/forum-205-1.html\">装备·团购</a>　<a href=\"/forum-334-1.html\">湖南百公里</a>　<a href=\"/forum-372-1.html\">湖南户外联盟</a><br />");
document.writeln("");
document.writeln("			<a href=\"/forum-94-1.html\"><span class=\"huang1\"><b>[38℃生活]</b></span></a>");
document.writeln("			<a href=\"/forum-126-1.html\">美食天下</a> <a href=\"/forum-164-1.html\">华声瘦客</a> <a href=\"/forum-27-1.html\">生活贴士</a> <a href=\"/forum-148-1.html\">科学探索</a> <a href=\"/forum-69-1.html\">电脑数码</a> <a href=\"/forum-115-1.html\">汽车沙龙</a> <a href=\"/forum-212-1.html\">法律沙龙</a> <a href=\"/forum-165-1.html\">谈股论金</a> <a href=\"/forum-340-1.html\">投资理财</a> <a href=\"/forum-228-1.html\">疯狂网购</a> <a href=\"/forum-347-1.html\">华声讯通</a> <a href=\"/forum-374-1.html\">艺术收藏</a><br />");
document.writeln("");
document.writeln("			<a href=\"/forum-1-1.html\"><span class=\"huang1\"><b>[华声文苑]</b></span></a>");
document.writeln("			<a href=\"/forum-7-1.html\">光阴故事|小说</a>　<a href=\"/forum-8-1.html\">不拍不快|杂文</a>　<a href=\"/forum-5-1.html\">荷韵轻香|散文</a>　<a href=\"/forum-120-1.html\">江湖客栈</a>　<a href=\"/forum-9-1.html\">清词古韵|诗词</a>　<a href=\"/forum-10-1.html\">现代诗谷|新诗</a>　<a href=\"/forum-124-1.html\">书法&绘画</a>　<a href=\"/forum-167-1.html\">文苑版务</a>　<br />");
document.writeln("			<a href=\"/forum-132-1.html\"><span class=\"huang1\"><b>[地方论坛]</b></span></a>");
document.writeln("			<a href=\"/forum-133-1.html\">混在深圳</a>　<a href=\"/forum-160-1.html\">混在广州</a>　<a href=\"/forum-134-1.html\">家在湖北</a>　<a href=\"/forum-23-1.html\">中山珠海</a>　<a href=\"/forum-142-1.html\">浙江社区</a>　<a href=\"/forum-145-1.html\">东北人家</a>　<a href=\"/forum-141-1.html\">江西社区</a>　<a href=\"/forum-147-1.html\">上海滩</a>　<a href=\"/forum-157-1.html\">情系齐鲁</a>　<a href=\"/forum-149-1.html\">河南社区</a><br /> ");
document.writeln("                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;");
document.writeln("			<a href=\"/forum-138-1.html\">闲居江苏</a>　<a href=\"/forum-143-1.html\">安徽论坛</a>　<a href=\"/forum-136-1.html\">情系陕西</a>　<a href=\"/forum-144-1.html\">三晋大地</a>　<a href=\"/forum-156-1.html\">巴山蜀水</a>　<a href=\"/forum-140-1.html\">福建论坛</a>　<a href=\"/forum-232-1.html\">河北驿站</a>　<a href=\"/forum-159-1.html\">漂在广西</a>　<a href=\"/forum-146-1.html\">彩云之南</a>　<a href=\"/forum-158-1.html\">北京不眠夜</a><br />");
document.writeln("			<a href=\"/forum-244-1.html\"><span class=\"huang1\"><b>[湖南论坛]</b></span></a>");
document.writeln("			<a href=\"http://www.0731go.cn/\">长沙网</a>　<a href=\"/forum-245-1.html\">株洲论坛</a>　<a href=\"/forum-246-1.html\">湘潭论坛</a>　<a href=\"forum-247-1.html\" target='_blank'>衡阳视点</a>　<a href=\"forum-363-1.html\" target='_blank'>雁城小苑</a>　<a href=\"forum-364-1.html\" target='_blank'>蒸湘生活</a>　<a href=\"/forum-248-1.html\">岳阳论坛</a>　<a href=\"/forum-249-1.html\">益阳论坛</a>　<a href=\"forum-379-1.html\" target='_blank'>今日常德</a>　<a href=\"forum-380-1.html\" target='_blank'>常德315</a>　<a href=\"forum-381-1.html\" target='_blank'>常德健康论坛</a><br />");
document.writeln("                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;");
document.writeln("			<a href=\"forum-251-1.html\" target='_blank'>邵阳社区</a>　<a href=\"forum-369-1.html\" target='_blank'>宝庆万象</a>　<a href=\"forum-370-1.html\" target='_blank'>服务邵阳</a>　<a href=\"forum-58-1.html\">经济风云</a>　<a href=\"/forum-252-1.html\">娄底论坛</a>　<a href=forum-366-1.html>我来说娄</a>　<a href=forum-367-1.html>娄底网事</a>　<a href=\"/forum-253-1.html\">永州论坛</a>　<a href=\"/forum-254-1.html\">郴州论坛</a>　<a href=\"/forum-255-1.html\">怀化论坛</a>　<a href=\"/forum-256-1.html\">湘西论坛</a><br />");
document.writeln("                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;");
document.writeln("                       <a href=\"/forum-257-1.html\">张家界论坛</a>  <a href=\"/forum-48-1.html\">兴湘论坛</a>  <a href=\"/forum-235-1.html\">华声房产</a>  <a href=\"forum-376-1.html\">湖南业余羽毛球俱乐部联赛</a><br />");
document.writeln("			");
document.writeln("			<a href=\"/forum-301-1.html\"><span class=\"huang1\"><b>[华声义工]</b></span></a>");
document.writeln("			<a href=\"/forum-302-1.html\">爱心同行</a>　<a href=\"/forum-303-1.html\">信息与意见</a>　<a href=\"/forum-305-1.html\">炎陵义工</a>　 <br /> ");
document.writeln("");
document.writeln("                               			");
document.writeln("			<a href=\"/forum-65-1.html\"><span class=\"huang1\"><b>[华声版务]</b></span></a>");
document.writeln("			<a href=\"/forum-41-1.html\">新手上路</a>　<a href=\"/forum-66-1.html\">投诉&amp;建议</a>　<a href=\"/forum-79-1.html\">版主交流</a>　<a href=\"/forum-86-1.html\">秘密花园</a>　<a href=\"/forum-297-1.html\">家园交流</a>　<a href=\"/forum-368-1.html\">掌上华声</a>");
document.writeln("                                <a href=\"/forum-14-1.html\"><span class=\"huang1\"><b>[华声故版]</b></span></a><br />");
document.writeln("			<a href=\"/forum-99-1.html\"><span class=\"huang1\"><b>[华声俱乐部]</b></span></a>");
document.writeln("			<a href=\"/forum-206-1.html\">线上活动</a> <a href=\"/forum-207-1.html\">华人基地</a>");
document.writeln("                                 <a href=\"/forum-242-1.html\">摄影俱乐部</a><br />");
document.writeln("");
document.writeln("			</td>");
document.writeln("		</tr>");
document.writeln("	</table>");
document.writeln("</div>");
document.writeln("");
document.writeln("<div class=\"headermenu_popup\" id=\"forumlistdiyfoot_menu\" style=\"height:auto;width:856px;margin:0px auto;\">");
document.writeln("	<table cellpadding=\"4\" cellspacing=\"0\" border=\"0\" style=\" width: 100%\">");
document.writeln("		<tr>");
document.writeln("			<td class=\"popupmenu_option2\" style=\"line-height:25px\"><a href=\"/forum-47-1.html\">");
document.writeln("			<span class=\"huang1\"><b>[时政军事]</b></span></a>");
document.writeln("			<a href=\"/forum-4-1.html\"><span class=\"huang1\"><b>[精彩贴图]</b></span></a>");
document.writeln("			<a href=\"/forum-20-1.html\"><span class=\"huang1\"><b>[影音帝国]</b></span></a>");
document.writeln("			<a href=\"/forum-13-1.html\"><span class=\"huang1\"><b>[轻松休闲]</b></span></a>");
document.writeln("			<a href=\"/forum-288-1.html\"><span class=\"huang1\"><b>[旅 游 区]</b></span></a>");
document.writeln("			<a href=\"/forum-94-1.html\"><span class=\"huang1\"><b>[38℃生活]</b></span></a>");
document.writeln("			<a href=\"/forum-1-1.html\"><span class=\"huang1\"><b>[华声文苑]</b></span></a>");
document.writeln("			<a href=\"/forum-132-1.html\"><span class=\"huang1\"><b>[地方论坛]</b></span></a><a href=\"/forum-65-1.html\"><span class=\"huang1\"><b>[华声版务]</b></span></a><a href=\"/forum-99-1.html\"><span class=\"huang1\"><b>[华声俱乐部]</b></span></a>");
document.writeln("			<a href=\"/forum-41-1.html\">新手上路</a> <a href=\"/forum-66-1.html\">投诉&amp;建议</a><br>");
document.writeln("			<div style=\"color:red;padding:0px; margin:0px;text-align: center;\">************************ 特色版面推荐：************************</div>");
document.writeln("			<a href=\"/forum-76-1.html\">辣眼时评</a>");
document.writeln("			<a href=\"/forum-49-1.html\">参考文摘</a> <a href=\"/forum-57-1.html\">图说历史</a>");
document.writeln("			<a href=\"/forum-24-1.html\">军事贴图</a> <a href=\"/forum-70-1.html\">军事杂谈</a>");
document.writeln("			<a href=\"/forum-25-1.html\">战史风云</a> <a href=\"/forum-61-1.html\">绝美图库</a>");
document.writeln("			<a href=\"/forum-105-1.html\">特效绝美</a> <a href=\"/forum-83-1.html\">搞笑图库</a>");
document.writeln("			<a href=\"/forum-22-1.html\">网友自拍</a> <a href=\"/forum-72-1.html\">摄友摄色</a>");
document.writeln("			<a href=\"/forum-78-1.html\">影视时空</a> <a href=\"/forum-77-1.html\">音乐地带</a>");
document.writeln("			<a href=\"/forum-55-1.html\">FLASH帝国</a> <a href=\"/forum-64-1.html\">娱乐八卦</a><br>");
document.writeln("			<a href=\"/forum-21-1.html\">千奇百怪</a>");
document.writeln("			<a href=\"/forum-52-1.html\">哈哈笑话</a> <a href=\"/forum-80-1.html\">异度空间</a> <a href=\"/forum-60-1.html\">灌水专区</a>");
document.writeln("			<a href=\"/forum-56-1.html\">智力考场</a> <a href=\"/forum-39-1.html\">驴友自助</a>");
document.writeln("			<a href=\"/forum-89-1.html\">情感酒廊</a>");
document.writeln("			<a href=\"/forum-7-1.html\">光阴故事|小说</a> <a href=\"/forum-8-1.html\">不拍不快|杂文</a> <a href=\"/forum-169-1.html\">小说迷</a>");
document.writeln("			<a href=\"/forum-133-1.html\">混在深圳</a> <a href=\"http://www.0731go.cn/\">长沙网</a>");
document.writeln("			<a href=\"/forum-244-1.html\">湖南论坛区</a> <a href=\"/forum-268-1.html\">女性区</a></td>");
document.writeln("		</tr>");
document.writeln("	</table>");
document.writeln("</div>");
document.writeln("<div class=\"headermenu_popup\" id=\"userinfo_menu\" style=\"height:auto;width:65px;margin:0px auto;display:none\">");
document.writeln("	<table cellpadding=\"4\" cellspacing=\"0\" border=\"0\" style=\" width: 100%\">");
document.writeln("	  <tr>");
document.writeln("	     <td class=\"popupmenu_option2\" style=\"line-height:25px\">");
document.writeln("	     <a href=\"http://home.voc.com.cn\">我的家园</a><br/>");
document.writeln("	     <a href=\"/my.php?item=threads\">我的帖子</a><br/>");
document.writeln("             <a href=\"/my.php?item=favorites&type=thread\">我的收藏</a><br/>");
document.writeln("             <a href=\"/memcp.php?action=buddylist\">好友列表</a><br/>");
document.writeln("             <a href=\"/magic.php\">我的道具</a><br/>");
document.writeln("             </td>");
document.writeln("	  </tr>");
document.writeln("	</table> ");
document.writeln("</div>");