(function(){if(typeof window.lezhi=="undefined"){var o=window.lezhi={},j=document;o.util={isIE6:/msie|MSIE 6/.test(navigator.userAgent),isIE:/msie|MSIE/.test(navigator.userAgent),getElemById:function(b){return j.getElementById(b)},getElemsByTagName:function(b,e){return b.getElementsByTagName(e)},isUndefined:function(b){return typeof b=="undefined"},isNotUndefined:function(b){return typeof b!="undefined"},arrayContains:function(b,e){for(var g=b.length;g--;)if(b[g]===e)return!0;return!1},lzhasClass:function(b,
e){return b.className&&this.arrayContains(b.className.split(" "),e)},addClass:function(b,e){this.lzhasClass(b,e)||(b.className+=(b.className?" ":"")+e)},removeClass:function(b,e){if(this.lzhasClass(b,e)){var g=b.className.split(" "),d;for(d=0;d<g.length;d++)g[d]==e&&g.splice(d++,1);b.className=g.join(" ")}},joinProperty:function(b,e){for(var g in e)b[g]=e[g];return b},createElement:function(b,e,g,d,l){var k=j.createElement(b);if(b=="a")k.href="javascript:;",k.target="_blank";if(e)k.id=e;if(g)k.className=
g;if(d)k.style.cssText=d;if(l)k.innerHTML=l;return k},htmlEncode:function(b){return b.replace(/&/g,"&amp;").replace(/\"/g,"&quot;").replace(/\'/g,"&#39;").replace(/</g,"&lt;").replace(/>/g,"&gt;")},getElemByClassName:function(b,e,g){for(var b=this.getElemsByTagName(b,e),d=[],e=0;e<b.length;e++)this.lzhasClass(b[e],g)&&d.push(b[e]);return d},getKeywords:function(){var b=this.getElemsByTagName(j,"META"),e,g="";for(e=0;e<b.length;e++)b[e].getAttribute("name")=="keywords"&&(g=encodeURIComponent(b[e].getAttribute("content")));
return g},getIndex:function(b,e){var g,d=-1;for(g in b)b[g]===e&&(d=g);return d},getHash:function(b){(b=/#(.+)/.exec(b))&&(b=b[0].slice(1));return b||""},loadStyle:function(b){var e=this.createElement("style");e.type="text/css";e.styleSheet?e.styleSheet.cssText=b:e.appendChild(j.createTextNode(b));this.getElemsByTagName(j,"head")[0].appendChild(e);return e},loadModule:function(b){if(!this.arrayContains(o.variables.requestedScripts,b)){!/\showup|\feeds/.test(b)&&!o.util.arrayContains(o.variables.ADS_JS_URL,
b)&&o.variables.requestedScripts.push(b);var e=this.createElement("script");e.type="text/javascript";e.charset="utf-8";e.src=b;this.getElemsByTagName(j,"head")[0].appendChild(e)}},mergeConfig:function(b,e){var g,d,j=o.variables,k=this.joinProperty({},b);for(g in e){d=e[g];if(this.isUndefined(d)||/(pic|highlight|showLogo|picBorderRadius)$/.test(g)&&typeof d!="boolean"||/(col|row|(pic|font|titleFont)Size|width|height|lineHeight|count)$/.test(g)&&(isNaN(d)||typeof d!="number"||d<0)||g=="type"&&!this.arrayContains(j.BSHARE_RECOMM_TYPES,
d)||g=="redirectType"&&!this.arrayContains(j.BSHARE_RECOMM_REDIRECT_TYPE,d)||g=="listType"&&!this.arrayContains(j.BSHARE_RECOMM_LISTTYPE,d)||g=="position"&&!this.arrayContains(j.BSHARE_RECOMM_POSITIONS,d))d=k[g];if(/(ht|rt|bd|hv|bg)color|titleBgColor/.test(g)&&d)try{d=decodeURIComponent(d)}catch(a){}if(g=="promote")try{d=decodeURIComponent(d).slice(0,8)}catch(m){d=d.slice(0,8)}!d&&/uuid|promote|sitePrefix|reason/.test(g)&&(k[g]="");d!==null&&!this.isUndefined(d)&&(k[g]=d)}return k},ready:function(b){if(document.addEventListener)b();
else if(document.attachEvent){document.attachEvent("onreadystatechange",function(){document.readyState==="complete"&&(document.detachEvent("onreadystatechange",arguments.callee),b.call())});window.attachEvent("onload",b);var e=!1;try{e=window.frameElement===null}catch(g){}document.documentElement.doScroll&&e&&function(){try{document.documentElement.doScroll("left")}catch(e){setTimeout(arguments.callee,10);return}b.call()}()}else window.onload=b},contains:function(b,e){if(b.length==0)return!1;else for(var g=
0;g<b.length;g++)if(b[g]==e)return!0},matchImage:function(){var b=j.images,e=0,g,d=j.body.scrollWidth/2,l,k,a,m,n;k=/combx|ad|comment|community|disqus|extra|foot|header|menu|remark|rss|shoutbox|sidebar|sponsor|ad-break|agegate|pagination|pager|popup|tweet|twitter/i;a=/and|article|body|column|main|shadow/i;m=o.util.getElemsByTagName(j,"*");n=m.length;for(var h=[],c=0;c<n;c++){l=m[c];var f=l.className+l.id;if(f.length>0&&f.search(k)!=-1&&f.search(a)==-1&&l.tagName!=="BODY"){var f=o.util.getElemsByTagName(l,
"img"),x=f.length;for(l=0;l<x;l++)h.push(f[l])}}for(l=0;l<b.length;l++)if(k=b[l],!o.util.contains(h,k)){a=k.offsetLeft;m=k.offsetTop;for(n=k.offsetParent;n&&n.nodeName!="BODY";)a+=n.offsetLeft,m+=n.offsetTop,n=n.offsetParent;a=a>0?a:-a;m=m>0?m:-m;k.width>=200&&k.height>=150&&a>40&&a<d&&m>40&&(a=Math.abs((d-a)*(1500-m)/(d*1500))*(k.width/k.height>2?0:k.width*k.height>12E4?12E4:k.width*k.height)*(/\.(gif|ico)$/.test(k.src)?0.4:1),a>e&&(e=a,g=k))}return g?g.src:""}}}})();var BSHARE_FEEDS_BASE="http://api.bshare.cn",LEZHI_PLUGIN_BASE="http://lzplugin.bshare.cn/plugin",LEZHI_STATIC_BASE="http://lzstatic.bshare.cn";
(function(){function o(){var m=a.util.getElemsByTagName(b,"script"),n,h,c,f={};for(n=0;n<m.length;n++)if(/(lz|lezhi)(Org|Tmp)?\.js/.test(m[n].src)&&(c=/\?(.*)|#(.*)/.exec(m[n].src))){c=c[0].slice(1).split("&");for(m=0;m<c.length;m++)if(h=c[m].split("="),(n=h[0])!="")h=h[1],/(col|row|(pic|font|titleFont)Size|width|height|lineHeight|count)$/.test(n)?h=+h:/(pic|highlight|showLogo|picBorderRadius|(title|font)Bold|(font|link)Underline)$/.test(n)&&(h=h=="true"),f[n]=h;break}return f}if(typeof window.lezhi.init==
"undefined"){var j=window,b=j.document,e=encodeURIComponent,g=decodeURIComponent,d=LEZHI_STATIC_BASE+"/plugin/",l=LEZHI_STATIC_BASE+"/plugin/img/",k=l+"default.gif",a=j.lezhi=j.lezhi.util.joinProperty(j.lezhi,{modules:{nodes:[],config:[],currentActivated:[],currentStop:[],sourceCount:[],isSetCount:[]},variables:{ADS_JS_URL:["http://static.mediav.com/js/mvf_g2.js"],ADS_JS_IDS_MEDIAV:{"300x250":"3cv6mn_1019305","200x200":"RtEzfw_1019411","610x100":"8yAhOD_1019306","660x90":"pMlk3O_1019412"},ADS_JS_WRAP_MEDIAV:"mediaV",
ADS_PRELOAD_DIV_ID:"lzPreloadDiv",ADS_CONTENT_ID:"mvdiv_1019305_holder",DEFAULT_PIC_URL:k,HOT_PIC_URL:l+"hot.png",LIKE_PIC_URL:l+"like.png",LIKED_PIC_URL:l+"liked.png",PAGEON_PIC_URL:l+"on.png",PAGEOFF_PIC_URL:l+"off.png",BSHARE_FEEDS_LINK:BSHARE_FEEDS_BASE+"/feeds/trending.json?callback=window.lezhi.callback",LEZHI_PLUGIN_LINK:LEZHI_PLUGIN_BASE+"/feeds?callback=window.lezhi.callback",LEZHI_LIKE_LINK:LEZHI_PLUGIN_BASE+"/like?callback=window.lezhi.likeResult",LEZHI_CORRECT_LINK:LEZHI_PLUGIN_BASE+"/correct?",
LEZHI_UTIL_LINK:d+"lz-util.js?v=20131206",LEZHI_ENGINE_LINK:d+"lz-engine.js?v=20131206",LEZHI_STYLEDEFAULT_LINK:d+"lz-style-default.js?v=20131206",LEZHI_STYLE300x250_LINK:d+"lz-style-300x250.js?v=20131206",LEZHI_STYLE200x200_LINK:d+"lz-style-200x200.js?v=20131206",LEZHI_STYLE250x250_LINK:d+"lz-style-250x250.js?v=20131206",LEZHI_STYLE125x125_LINK:d+"lz-style-125x125.js?v=20131206",LEZHI_STYLE610x100_LINK:d+"lz-style-610x100.js?v=20131206",ADMAX_LINK:"http://static.buzzads.com/js/a/admax.js",BSHARE_RECOMM_TYPES:["fixed",
"slide"],BSHARE_RECOMM_POSITIONS:["left","right"],BSHARE_RECOMM_REDIRECT_TYPE:["_self","_blank"],BSHARE_RECOMM_LISTTYPE:["disc","square","none"],STYLETYPE_DEFAULT:"lz-style-default",STYLETYPE_300x250:"lz-style-300x250",STYLETYPE_200x200:"lz-style-200x200",STYLETYPE_250x250:"lz-style-250x250",STYLETYPE_125x125:"lz-style-125x125",STYLETYPE_610x100:"lz-style-610x100",STYLETYPE_CUSTOM:"lz-style-custom",BSHARE_RECOMM_SOURCES_NAMES:{trending:"\u6700\u70ed\u6587\u7ae0",insite:"\u60a8\u53ef\u80fd\u4e5f\u559c\u6b22",itemcf:"\u4e2a\u4eba\u63a8\u8350",
personalized:"\u60a8\u53ef\u80fd\u4e5f\u559c\u6b22"},BSHARE_RECOMM_SOURCES_FIRSTNAMES:/(insite|itemcf)$/,adsIds:[],adsPreloadDone:[],adsShow:!1,currentPage:[],referrer:b.referrer,requestedScripts:[],trendingShow:!1,vid:""},config:{global:{uuid:"",promote:"??????????????????",col:5,row:2,pic:!0,type:"fixed",picSize:88,fontSize:12,sitePrefix:"",defaultPic:k,position:"right",source:"insite",url:e(b.location.href),title:b.title,hash:g(j.location.hash.slice(1)),htcolor:"#333",rtcolor:"#333",bdcolor:"#DADADA",hvcolor:"#333",
highlight:!1,showLogo:!0,mock:!1,count:0,adCount:0,autoPageTime:6E3,like:!1,width:0,height:0,titleBgColor:"#fff",titleFontSize:12,titleBold:!1,fontBold:!1,fontUnderline:!1,linkUnderline:!1,redirectType:"_blank",picMatch:"insite",bgcolor:"#fff",picBorderRadius:!0,lineHeight:15,listType:"disc"}},init:function(){var m;a.modules.nodes=a.util.getElemByClassName(b,"div","lz-module");if(a.util.getElemById("bShareRecommDiv"))m=a.modules.nodes.push(a.util.getElemById("bShareRecommDiv")),a.modules.nodes[m-
1].oldVersionId=!0},start:function(){a.modules.nodes.length!=0&&a.util.loadModule(a.variables.LEZHI_ENGINE_LINK)},switchTo:function(b,n,h,c,f){var e=b.parentNode,d,g=[],j=0;c>1?(d=a.util.getElemByClassName(e.parentNode,"div","bShareRecommDiv3")[0],g=a.util.getElemByClassName(e.parentNode,"div","bShareRecommPages")[0].getElementsByTagName("span"),j=1):d=e.parentNode;d=d.childNodes;var e=e.getElementsByTagName("li"),k=d.length,l=0;c>1?k--:l=h==="slide"?2:1;c<=0&&a.modules.config[0].like&&l++;for(h=
0;h<e.length;++h)e[h].className="";b.className="activated";for(h=l;h<k;++h)d[h].getAttribute("sourceType")==n?(d[h].style.display="block",a.util.addClass(d[h],"activated"),j=d[h].getAttribute("cp")||0):(d[h].style.display="none",a.util.removeClass(d[h],"activated"));for(h=0;h<g.length;h++)g[h].className=j==h?"on":"";if(!a.variables.trendingShow&&n=="trending")a.stats.view("trending",f),a.variables.trendingShow=!0},autoPage:function(b,e,h){var c=a.util.getElemsByTagName(a.util.getElemByClassName(a.modules.nodes[b],
"div","bShareRecommPages")[0],"SPAN");a.util.isUndefined(a.variables.currentPage[b])&&(a.variables.currentPage[b]=0);a.switchPage(c[a.variables.currentPage[b]],a.variables.currentPage[b],h,b,void 0,e)},switchPage:function(b,e,h,c,f,d){var f=a.util.getElemByClassName(b.parentNode.parentNode.parentNode,"div","bShareRecommDiv3")[0],g=100*-e,j=a.util.getElemByClassName(f,"div","activated")[0],f=[],k=a.util.getIndex(a.modules.nodes,b.parentNode.parentNode.parentNode),l,o=b.parentNode.getElementsByTagName("span"),
s,p,q,w=(e+1)*h,y=o.length,t;a.variables.currentPage[c]=e;if(a.modules.currentStop[c])return!1;if(j)s=a.util.getElemsByTagName(j,"li"),p=parseInt(j.style.left||0);else return!1;for(q=0;q<y;q++)a.util.removeClass(o[q],"on");a.util.addClass(b,"on");l=function(){var b=g>p,f=!b?5:10;if(p==g)a.modules.currentStop[c]=!1,a.modules.currentStop[c]||(a.variables.currentPage[c]>=d-1?a.variables.currentPage[c]=0:a.variables.currentPage[c]++,setTimeout(function(){a.autoPage(c,d,h,a.modules.config[c].autoPageTime)},
a.modules.config[c].autoPageTime));else{p=b?p+f:p-f;if(b&&p>g||!b&&p<g)p=g;j.setAttribute("cp",e);j.style.left=p+"%";setTimeout(l,10)}};a.modules.currentStop[c]=!0;l();for(q=w-h;q<w;q++)if(s[q]&&(t=s[q].getAttribute("adEntryId")))if(t&&!a.util.arrayContains(a.variables.adsIds[k],t))a.variables.adsIds[k].push(t),f.push(t);else return!0;else return!0;a.stats.adsView(k,f);return!0},stats:{view:function(b,d){var h=a.modules.config[d],h=["uuid="+h.uuid,"url="+h.url,"ref="+b,"type="+h.type,"pic="+h.pic,
"title="+e(h.title.replace(/#blz-insite/g,"")),"timestamp="+ +new Date],h=h.join("&");a.util.loadModule(LEZHI_PLUGIN_BASE+"/showup?"+h)},adsView:function(b,e){var d=a.modules.config[b],d=["uuid="+d.uuid,"url="+d.url,"timestamp="+ +new Date],d=d.join("&")+(a.variables.adsShow?"&adEntryIds="+e.join(","):"");a.util.loadModule(LEZHI_PLUGIN_BASE+"/adShowup?"+d)}},ads:{preload:function(e,d,h){var c=300,f=250;d.lezhiStyle==a.variables.STYLETYPE_200x200?f=c=200:d.lezhiStyle==a.variables.STYLETYPE_250x250?
c=250:d.lezhiStyle==a.variables.STYLETYPE_125x125?f=c=125:d.lezhiStyle==a.variables.STYLETYPE_610x100&&(c=610,f=100);j.mediav_ad_wrap=a.variables.ADS_PRELOAD_DIV_ID+e;j.mediav_ad_pub=a.variables.ADS_JS_IDS_MEDIAV[c+"x"+f];j.mediav_ad_width=c;j.mediav_ad_height=f;f=a.util.createElement("div",a.variables.ADS_PRELOAD_DIV_ID+e,"","width:"+c+"px;height:"+f+"px;background:#eee;");c=a.util.createElement("script");c.src=h;c.type="text/javascript";c.charset="utf-8";c.onload=function(){a.ads.preloadCb(e)};
c.onreadystatechange=function(){/complete|loaded/.test(this.readyState)&&a.ads.preloadCb(e)};d.appendChild(f);a.util.getElemsByTagName(b,"head")[0].appendChild(c)},preloadCb:function(b){a.variables.adsPreloadDone[b]=!0}},getConfigurations:function(b){function d(a){return s(a.col)||s(a.row)||s(a.count)}var h=j.bshare_recomm_config||{},c=j.lezhi_config||{},f=j.lezhi_style_core||{},g=j.lezhi_style_default||{},k=j.lezhi_style_300x250||{},l=j.lezhi_style_200x200||{},u=j.lezhi_style_250x250||{},v=j.lezhi_style_125x125||
{};lezhiStyle610x100Config=j.lezhi_style_610x100||{};lezhiStyleCustomConfig=j.lezhi_style_custom||{};var r=a.util.isUndefined,s=a.util.isNotUndefined;lezhiStyleDefaultConfigGlobal=g.global||{};lezhiStyle300x250ConfigGlobal=k.global||{};lezhiStyle200x200ConfigGlobal=l.global||{};lezhiStyle250x250ConfigGlobal=u.global||{};lezhiStyle125x125ConfigGlobal=v.global||{};lezhiStyle610x100ConfigGlobal=lezhiStyle610x100Config.global||{};lezhiStyleCustomConfigGlobal=lezhiStyleCustomConfig.global||{};a.config.global=
a.util.mergeConfig(a.config.global,a.variables.configPre);a.config.global=a.util.mergeConfig(a.config.global,o());if(b)a.config.global=a.util.mergeConfig(a.config.global,b);b=a.util.mergeConfig({},h);b=a.util.mergeConfig(b,c.global||{});b=a.util.mergeConfig(b,f.global||{});if(b.url&&a.config.global.url!=b.url)a.config.global.hash=a.util.getHash(b.url),b.url=e(b.url);a.config.global=a.util.mergeConfig(a.config.global,b);for(c=0;c<a.modules.nodes.length;c++)if(a.modules.isSetCount[c]=d(b),f=a.modules.nodes[c],
a.modules.config[c]=a.util.mergeConfig(a.modules.config[c],a.config.global),a.util.lzhasClass(f,a.variables.STYLETYPE_DEFAULT)||f.oldVersionId){if(a.modules.config[c]=a.util.mergeConfig(a.modules.config[c],lezhiStyleDefaultConfigGlobal),a.modules.nodes[c].lezhiStyle=a.variables.STYLETYPE_DEFAULT,a.modules.isSetCount[c]||(a.modules.isSetCount[c]=d(lezhiStyleDefaultConfigGlobal)),f.id&&!r(g[f.id]))a.modules.nodes[c].idConfig=!0,a.modules.config[c]=a.util.mergeConfig(a.modules.config[c],g[f.id]),a.modules.isSetCount[c]||
(a.modules.isSetCount[c]=d(g[f.id]))}else if(a.util.lzhasClass(f,a.variables.STYLETYPE_300x250)){if(a.modules.config[c].adEnabled=!0,a.modules.config[c].adPreload=!1,a.modules.config[c]=a.util.mergeConfig(a.modules.config[c],lezhiStyle300x250ConfigGlobal),a.modules.nodes[c].lezhiStyle=a.variables.STYLETYPE_300x250,a.modules.isSetCount[c]||(a.modules.isSetCount[c]=d(lezhiStyle300x250ConfigGlobal)),f.id&&!r(k[f.id]))a.modules.nodes[c].idConfig=!0,a.modules.config[c]=a.util.mergeConfig(a.modules.config[c],
k[f.id]),a.modules.isSetCount[c]||(a.modules.isSetCount[c]=d(k[f.id]))}else if(a.util.lzhasClass(f,a.variables.STYLETYPE_200x200)){if(a.modules.config[c].adEnabled=!0,a.modules.config[c].adPreload=!1,a.modules.config[c]=a.util.mergeConfig(a.modules.config[c],lezhiStyle200x200ConfigGlobal),a.modules.nodes[c].lezhiStyle=a.variables.STYLETYPE_200x200,a.modules.isSetCount[c]||(a.modules.isSetCount[c]=d(lezhiStyle200x200ConfigGlobal)),f.id&&!r(l[f.id]))a.modules.nodes[c].idConfig=!0,a.modules.config[c]=
a.util.mergeConfig(a.modules.config[c],l[f.id]),a.modules.isSetCount[c]||(a.modules.isSetCount[c]=d(l[f.id]))}else if(a.util.lzhasClass(f,a.variables.STYLETYPE_250x250)){if(a.modules.config[c].adEnabled=!0,a.modules.config[c].adPreload=!1,a.modules.config[c]=a.util.mergeConfig(a.modules.config[c],lezhiStyle250x250ConfigGlobal),a.modules.nodes[c].lezhiStyle=a.variables.STYLETYPE_250x250,a.modules.isSetCount[c]||(a.modules.isSetCount[c]=d(lezhiStyle250x250ConfigGlobal)),f.id&&!r(u[f.id]))a.modules.nodes[c].idConfig=
!0,a.modules.config[c]=a.util.mergeConfig(a.modules.config[c],u[f.id]),a.modules.isSetCount[c]||(a.modules.isSetCount[c]=d(u[f.id]))}else if(a.util.lzhasClass(f,a.variables.STYLETYPE_125x125)){if(a.modules.config[c].adEnabled=!0,a.modules.config[c].adPreload=!1,a.modules.config[c]=a.util.mergeConfig(a.modules.config[c],lezhiStyle125x125ConfigGlobal),a.modules.nodes[c].lezhiStyle=a.variables.STYLETYPE_125x125,a.modules.isSetCount[c]||(a.modules.isSetCount[c]=d(lezhiStyle125x125ConfigGlobal)),f.id&&
!r(v[f.id]))a.modules.nodes[c].idConfig=!0,a.modules.config[c]=a.util.mergeConfig(a.modules.config[c],v[f.id]),a.modules.isSetCount[c]||(a.modules.isSetCount[c]=d(v[f.id]))}else if(a.util.lzhasClass(f,a.variables.STYLETYPE_610x100)){if(a.modules.config[c].adEnabled=!0,a.modules.config[c].adPreload=!1,a.modules.config[c]=a.util.mergeConfig(a.modules.config[c],lezhiStyle610x100Config.global||{}),a.modules.nodes[c].lezhiStyle=a.variables.STYLETYPE_610x100,a.modules.isSetCount[c]||(a.modules.isSetCount[c]=
d(lezhiStyle610x100ConfigGlobal)),f.id&&!r(lezhiStyle610x100Config[f.id]))a.modules.nodes[c].idConfig=!0,a.modules.config[c]=a.util.mergeConfig(a.modules.config[c],lezhiStyle610x100Config[f.id]),a.modules.isSetCount[c]||(a.modules.isSetCount[c]=d(lezhiStyle610x100Config[f.id])),a.modules.config[c]=a.util.mergeConfig(a.modules.config[c],lezhiStyle610x100Config[f.id]),a.modules.isSetCount[c]||(a.modules.isSetCount[c]=d(lezhiStyle610x100Config[f.id]))}else if(a.util.lzhasClass(f,a.variables.STYLETYPE_CUSTOM)&&
(a.modules.config[c]=a.util.mergeConfig(a.modules.config[c],lezhiStyleCustomConfig.global||{}),a.modules.nodes[c].lezhiStyle=a.variables.STYLETYPE_CUSTOM,a.modules.isSetCount[c]||(a.modules.isSetCount[c]=d(lezhiStyleCustomConfigGlobal)),f.id&&!r(lezhiStyleCustomConfig[f.id])))a.modules.nodes[c].idConfig=!0,a.modules.config[c]=a.util.mergeConfig(a.modules.config[c],lezhiStyleCustomConfig[f.id]),a.modules.isSetCount[c]||(a.modules.isSetCount[c]=d(lezhiStyleCustomConfig[f.id]))},like:function(){var b=
a.modules.config[0],b=["uuid="+b.uuid,"url="+b.url,"title="+e(b.title.replace(/#blz-insite/g,"")),"keywords="+a.util.getKeywords(),"timestamp="+ +new Date];a.util.loadModule(a.variables.LEZHI_LIKE_LINK+"&"+b.join("&"))},likeResult:function(b){if(b){var b=a.util.getElemByClassName(a.modules.nodes[0],"div","like")[0],d=b.getElementsByTagName("DIV")[0],e=b.getElementsByTagName("DIV")[1];a.util.addClass(b,"liked");d.onclick=null;e.innerHTML=Number(e.innerHTML)+1}}});a.variables.configPre=o();a.init();
(function(){var b,d=j.location.host,e=function(a,d,e,g,h,j){b='<style>.lz-style-610x100,.lz-style-300x250{display:none !important;}</style><script language="javascript" type="text/javascript">yigao_title_color = "null";yigao_content_color = "null";yigao_background_color = "null";yigao_border_color = "D9D9D9";yigao_title_bold = "0";yigao_content_bold = "0";yigao_title_underline = "0";yigao_content_underline = "0";yigao_width = '+d+";yigao_height = "+a+';yigao_sid = "'+e+'";yigao_msid = "'+g+'";yigao_uid = 79996;yigao_zid = '+
h+";yigao_pid = "+j+';yigao_type = 1;yigao_adamount = 1;yigao_cols = 1;<\/script><script language="javascript" src="http://monitor.yigao.com/info2.js"><\/script>';document.write(b)};for(i=0;i<a.modules.nodes.length;++i)a.modules.nodes[i].className.indexOf("lz-style-610x100")>-1?(d.indexOf("gmw.cn")>-1||d.indexOf("qa.buzzinate.com")>-1)&&e(610,100,"cdca3400cb80f615","ab5a0128d528c95f","144413",33):a.modules.nodes[i].className.indexOf("lz-style-300x250")>-1&&(d.indexOf("yzz.cn")>-1?e(300,250,"74325ab147bcab39",
"1cebda54493f1f53","144415",6):d.indexOf("newhua.com")>-1&&e(300,250,"02ecc5803f290c02","4df296a80db8d7e1","144414",6))})();a.util.ready(a.start)}})();
